# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Follow the instructions below to see how to use this script to compare logs / spans
# generated by this instrumentation with another version of the instrumentation (one from your local branch for example).

# Update `diff_instrumentation_changes.toml` to point to your local branch with local changes. Run uv sync to install the dependencies in a venv.
# Then run `uv run diff_instrumentation_changes.py` after updating the variables below: i.e. the project ID, prompt and model, tools etc..
# The script will create a test_span.textproto and test_log.textproto in the current working directory that the instrumenttion
# generated.

# Then you can update `diff_instrumentation_changes.toml` to point to the original branch and compare the generated
# test_span.textproto and test_log.textproto with the ones generated when running this script with the new branch.
# The test_span.textproto and test_log.textproto files will be overwritten each time the script is run.

import os

from google import genai
from google.genai import types
from opentelemetry.instrumentation.google_genai import (
    GoogleGenAiSdkInstrumentor,
)
import time
from opentelemetry.sdk._logs import LoggerProvider
from opentelemetry import trace
from opentelemetry.sdk._logs.export import (
    SimpleLogRecordProcessor,
)

from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import SimpleSpanProcessor
from opentelemetry.exporter.otlp.proto.common._internal import trace_encoder, _log_encoder
from google.protobuf import text_format
from opentelemetry.sdk._logs._internal.export.in_memory_log_exporter import (
    InMemoryLogExporter,
)
from opentelemetry import _logs as logs
from opentelemetry.sdk.trace.export.in_memory_span_exporter import (
    InMemorySpanExporter,
)


os.environ["OTEL_SEMCONV_STABILITY_OPT_IN"] = "gen_ai_latest_experimental"
os.environ["OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT"] = "SPAN_AND_EVENT""

PROJECT_ID = "my-project-id"
LOCATION = "us-central1"
MODEL = "gemini-2.5-flash"
PROMPT = "Can you add 2 and 8"

resource = Resource.create(attributes={SERVICE_NAME: "write-to-file-example"})
in_memory_log_exporter = InMemoryLogExporter()
in_memory_span_exporter = InMemorySpanExporter()

trace_provider = TracerProvider(resource=resource)
trace_provider.add_span_processor(
    SimpleSpanProcessor(in_memory_span_exporter)
)
trace.set_tracer_provider(trace_provider)
logger_provider = LoggerProvider(resource=resource)
logger_provider.add_log_record_processor(
    SimpleLogRecordProcessor(in_memory_log_exporter)
)
logger_provider.add_log_record_processor(
    SimpleLogRecordProcessor(in_memory_log_exporter)
)
logs.set_logger_provider(logger_provider)

def write_logs_to_file(file_name: str):
    logs = in_memory_log_exporter.get_finished_logs()
    log_proto = _log_encoder.encode_logs(logs)
    with open(os.path.join(os.getcwd(), file_name + ".textproto"), "w") as f:
        f.write(text_format.MessageToString(log_proto))

def write_spans_to_file(file_name: str):
  spans = in_memory_span_exporter.get_finished_spans()
  span_proto = trace_encoder.encode_spans(spans)
  with open(os.path.join(os.getcwd(), file_name + ".textproto"), "w") as f:
    f.write(text_format.MessageToString(span_proto))    

def add(a: int, b:int) -> int:
    return a + b

def main():
    GoogleGenAiSdkInstrumentor().instrument()
    client = genai.Client(
        vertexai=True, project=PROJECT_ID, location=LOCATION,
    )
    response = client.models.generate_content(
        model=MODEL,
        contents=PROMPT,
        config=types.GenerateContentConfig(tools=[add]),
    )
    write_spans_to_file("test_span")
    write_logs_to_file("test_log")
    print(response.text)


if __name__ == "__main__":
    main()